export enum Permission {
    CREATE_CAMPAIGN = 'CREATE_CAMPAIGN',
    EDIT_CAMPAIGN = 'EDIT_CAMPAIGN',
    VIEW_PORTFOLIO = 'VIEW_PORTFOLIO',
    EDIT_PORTFOLIO = 'EDIT_PORTFOLIO',
    VIEW_ANALYTICS = 'VIEW_ANALYTICS',
}
